stages:
  - test
  - build
  - s3
  - trigger

variables:
  BUILD: "yes"
  TEST: "yes"

include:
  - project: mattermost/ci/mattermost-webapp
    ref: release-5.35
    file: private.yml

empty:
  stage: test
  script:
    - echo "empty"

test: #todo check on how to create junit.xml, there currently is none
  stage: test
  image: $CI_REGISTRY/mattermost/ci/images/mattermost-build-webapp:20200829_node-10.22
  cache:
    key:
      files:
        - package.json
      prefix: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline

    # i18n
    - cp i18n/en.json /tmp/en.json
    - mkdir -p /tmp/fake-mobile-dir/assets/base/i18n/
    - echo '{}' > /tmp/fake-mobile-dir/assets/base/i18n/en.json

    - npm run mmjstool -- i18n extract-webapp --webapp-dir . --mobile-dir /tmp/fake-mobile-dir
    - diff /tmp/en.json i18n/en.json
    # Address weblate behavior which does not remove whole translation item when translation string is set to empty
    - npm run mmjstool -- i18n clean-empty --webapp-dir . --mobile-dir /tmp/fake-mobile-dir --check
    - npm run mmjstool -- i18n check-empty-src --webapp-dir . --mobile-dir /tmp/fake-mobile-dir

    - rm -rf tmp

    # typescript
    - npm run check-types

    # lint
    - npm run check

    # unit tests
    - npm run test-ci
  timeout: 3 hours
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $TEST == "yes"'
